src/Form/GithubAccountForm.php
<?php

namespace Drupal\amazee_test\Form;

use Drupal\Core\Form\ConfigFormBase;
use Drupal\Core\Form\FormStateInterface;

/**
 * Class GithubAccountForm.
 *
 * @package Drupal\amazee_test\Form
 */
class GithubAccountForm extends ConfigFormBase {

  /**
   * {@inheritdoc}
   */
  protected function getEditableConfigNames() {
    return [
      'amazee_test.githubaccount',
    ];
  }

  /**
   * {@inheritdoc}
   */
  public function getFormId() {
    return 'github_account_form';
  }

  /**
   * {@inheritdoc}
   */
  public function buildForm(array $form, FormStateInterface $form_state) {
    $config = $this->config('amazee_test.githubaccount');
    $form['user_login'] = array(
      '#type' => 'textfield',
      '#title' => $this->t('User login'),
      '#description' => $this->t('The use login example: benellefimostfa'),
      '#maxlength' => 64,
      '#size' => 64,
      '#default_value' => $config->get('user_login'),
    );
    return parent::buildForm($form, $form_state);
  }

  /**
   * {@inheritdoc}
   */
  public function validateForm(array &$form, FormStateInterface $form_state) {
    parent::validateForm($form, $form_state);
  }

  /**
   * {@inheritdoc}
   */
  public function submitForm(array &$form, FormStateInterface $form_state) {
    parent::submitForm($form, $form_state);

    $this->config('amazee_test.githubaccount')
      ->set('user_login', $form_state->getValue('user_login'))
      ->save();
  }

}

Tests/Controller/StargazersApiControllerTest.php
<?php

namespace Drupal\amazee_test\Tests;

use Drupal\simpletest\WebTestBase;

/**
 * Provides automated tests for the amazee_test module.
 */
class StargazersApiControllerTest extends WebTestBase {

  /**
   * {@inheritdoc}
   */
  public static function getInfo() {
    return array(
      'name' => "amazee_test StargazersApiController's controller functionality",
      'description' => 'Test Unit for module amazee_test and controller StargazersApiController.',
      'group' => 'Other',
    );
  }

  /**
   * {@inheritdoc}
   */
  public function setUp() {
    parent::setUp();
  }

  /**
   * Tests amazee_test functionality.
   */
  public function testStargazersApiController() {
    // Check that the basic functions of module amazee_test.
    $this->assertEquals(TRUE, TRUE, 'Test Unit Generated via App Console.');
  }

}

src/Controller/GithubApiController.php
<?php

namespace Drupal\amazee_test\Controller;

use Drupal\amazee_test\GithubApiService;
use Drupal\Core\Controller\ControllerBase;
use Symfony\Component\DependencyInjection\ContainerInterface;

/**
 * Class GithubApiController.
 *
 * @package Drupal\amazee_test\Controller
 */
class GithubApiController extends ControllerBase {
  /**
   * @var GithubApiService
   */
  private $githubApi;

  /**
   * GithubApiController constructor.
   *
   * @param \Drupal\amazee_test\GithubApiService $githubApi
   */
  public function __construct(GithubApiService $githubApi) {

    $this->githubApi = $githubApi;
  }

  /**
   * @param \Symfony\Component\DependencyInjection\ContainerInterface $container
   * @return static
   */
  public static function create(ContainerInterface $container) {

    $githubApi = $container->get('github_api');

    return new static($githubApi);
  }

  /**
   * @return array
   */
  public function getUser() {

    $content = $this->githubApi->getUser();

    return array(
      '#theme' => 'github_user',
      '#content' => $content,
    );
  }

  /**
   * @return array
   */
  public function getIssues($language) {
    // Convert object to array.
    $content = (array) $this->githubApi->getIssues($language);
    // Get first 10 items.
    $items = array_slice($content['items'], 0, 10, TRUE);

    return array(
      '#theme' => 'github_issues',
      '#items' => $items,
    );
  }

  /**
   * @return array
   */
  public function getRepos($language) {
    // Convert object to array.
    $content = (array) $this->githubApi->getRepos($language);
    // Get first 10 items.
    $items = array_slice($content['items'], 0, 10, TRUE);

    return array(
      '#theme' => 'github_repos',
      '#items' => $items,
    );
  }

  /**
   * @return array
   */
  public function getProjects() {
    // Convert object to array.
    $content = (array) $this->githubApi->getRepos('all');
    // Get first 10 items.
    $items = array_slice($content['items'], 0, 10, TRUE);
    $currencies = $this->getCurrencies();

    return array(
      '#theme' => 'github_projects',
      '#items' => $items,
      '#currencies' => $currencies,
    );
  }

  /**
   * @return \Drupal\Core\Config\Config
   */
  public function getCurrencies() {
    $url =
      'http://www.apilayer.net/api/live?access_key=8ac159821a62e58b7ef1a670063a0f95';

    $content = (array) $this->githubApi->getRequest($url);
    $content = (array) $content['quotes'];
    $currencies['GBP'] = $content['USDGBP'];
    $currencies['EUR'] = $content['USDEUR'];
    $currencies['CHF'] = $content['USDCHF'];
    return $currencies;
  }
}

templates/github-issues.html.twig
{% for item in items %}
  <div>
    <p>{{ item.title }}</p>
    <p>by: {{ item.user.login }}</p>
    <p>
      <img src="{{ item.user.avatar_url }}" height="100px" width="100px">
    </p>
    <p>Number of omments: {{ item.comments }}</p>
    <p>{{ item.body[:300] }}</p>
    <p><a href="{{ item.html_url }}" target="_blank">View on github</a></p>
  </div>
{% endfor %}

templates/github-projects.html.twig
<table>
  <tr>
    <th>General info</th>
    <th>Watchers count</th>
    <th>Forks</th>
    <th>Wiki</th>
    <th>Has downloads</th>
    <th>Has Issues</th>
    <th>Total</th>
  </tr>
  {% set global_count = 0 %}
  {% for item in items %}
    {% set row_count = 0 %}
    <tr>
      <td>
        {{ item.name }},
        {{ item.stargazers_count }},
        {{ item.language }}
      </td>
      <td>
        {{ item.watchers_count }}
        {% set row_count = row_count + item.watchers_count %}
      </td>
      <td>
        {{ item.forks }}
        {% set row_count = row_count + item.forks %}
      </td>
      <td>
        {% set wiki = item.has_wiki ? '50' : '0' %}
        {{ wiki }}
        {% set row_count = row_count + wiki %}

      </td>
      <td>
        {% set download = item.has_downloads ? '100' : '0' %}
        {{ download }}
        {% set row_count = row_count + download %}

      </td>
      <td>
        {% set issues = item.has_issues ? '10' : '0' %}
        {{ issues }}
        {% set row_count = row_count + issues %}
      </td>
      <td>
        {{ row_count }} USD
      </td>
    </tr>
    {% set global_count = global_count + row_count %}
  {% endfor %}
  <tr>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td>
      <p>{{ global_count }} USD</p>
      <p>{{ global_count * currencies.GBP }} GBP</p>
      <p>{{ global_count * currencies.EUR }} EUR</p>
      <p>{{ global_count * currencies.CHF }} CHF</p>
    </td>
  </tr>
</table>

templates/github-repos.html.twig
{% for item in items %}
  <div>
    <p>{{ item.name }}</p>
    <p>by: {{ item.owner.login }}</p>
    <p>
      <img src="{{ item.owner.avatar_url }}" height="100px" width="100px">
    </p>
    <p>Stargazers count: {{ item.stargazers_count }}</p>
    <p><a href="{{ item.html_url }}" target="_blank">View on github</a></p>
  </div>
{% endfor %}

templates/github-user.html.twig
{% if content.avatar_url is not empty %}
  <img src="{{ content.avatar_url }}"  height="42" width="42">
{% endif %}

<div>id: {{ content.id }} </div>

<div>login: {{ content.login }}</div>